apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: spring-realm
    files:
      - ./spring-realm.json
      - ./upload-realm-keycloak.sh
    behavior: create

generatorOptions:
  disableNameSuffixHash: false