logging:
  level:
    root: DEBUG


server:
  port: 8081
#  servlet:
#    context-path: "/v1/api"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring

keycloak:
  parameters:
    client-id: spring-boot-app


#      client:
#        registration:
#          keycloak:
#            client-id: spring-boot-app
#            authorization-grant-type: authorization_code
jwt:
  auth:
    converter:
      resource-id: ${keycloak.parameters.client-id}
      principal-attribute: preferred_username

