logging:
  level:
    root: trace

management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: ${MANAGEMENT_SERVER_PORT:9090}

  endpoint:
    health:
      show-details: ALWAYS

server:
  port: ${SERVER_PORT:8081}
#  servlet:
#    context-path: "/v1/api"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.parameters.serverAddress}/realms/spring

keycloak:
  parameters:
    client-id: spring-boot-app
    serverAddress: ${KEYCLOAK_SERVER_ADDRESS:http://localhost:8080}
    adminUser: ${KC_ADMIN_USER:admin}
    adminPassword: ${KC_ADMIN_PASS:admin}

#      client:
#        registration:
#          keycloak:
#            client-id: spring-boot-app
#            authorization-grant-type: authorization_code
jwt:
  auth:
    converter:
      resource-id: ${keycloak.parameters.client-id}
      principal-attribute: preferred_username

