apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-app
  name: keycloak-app
spec:
  ports:
  - name: keycloak-app-http
    port: 8080
    protocol: TCP
    targetPort: keycloak-http
  selector:
    app: springboot-keycloak-app
  type: ClusterIP

