apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo

metadata:
  name: build-keycloak-with-realm

namespace: keycloak-spring

resources:
  - namespace.yaml
  - ../keycloak-config
  - deployment.yaml
  - keycloak-svc.yaml
  - springboot-svc.yaml



