apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  ports:
    - name: springboot-app-http
      port: 8081
      protocol: TCP
      targetPort: http
  selector:
    app: springboot-keycloak-app
  type: ClusterIP

